name: Python package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        numpy-version: ["2.1.3"]
        environment-manager: ["conda", "pip"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.environment-manager == 'pip' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Conda ${{ matrix.python-version }}
      if: ${{ matrix.environment-manager == 'conda' }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env
        auto-activate-base: false

    - name: Install dependencies with pip
      if: ${{ matrix.environment-manager == 'pip' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==${{ matrix.numpy-version }}
        python -m pip install flake8 pytest
        # Install mdtraj if numpy compatibility is resolved
        # python -m pip install mdtraj
        python -m pip install .
        if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi

    - name: Install dependencies with Conda
      if: ${{ matrix.environment-manager == 'conda' }}
      run: |
        conda install --yes numpy=${{ matrix.numpy-version }} flake8 pytest
        conda install --yes pip
        pip install --upgrade pip
        # Install mdtraj if numpy compatibility is resolved
        # pip install mdtraj
        pip install .
        if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest pytim/ --doctest-modules

